#version 450
// Native Vulkan backend: the updated water surface. Port of Water/Shaders/WaterModern.hlsl (the Direct3D shader of the DXVK path),
// built twice: -DRIVER for river polygons, -DTRAPEZOID for area water (the sea).
// The engine feeds it exactly like the Direct3D shader: stage textures 0..6, pixel shader constants c1..c23, and texture coordinate
// sets generated by stage transforms (4 = projected position, 5 = height map uv, 6 = camera space position).

layout(std140, set = 0, binding = 0) uniform Draw
{
	mat4 wvp;
	vec4 viewport;
	vec4 textureFactor;
	uvec4 flags;
	vec4 alphaRef;
	uvec4 stage[8];
	mat4 world;
	vec4 matDiffuse;
	vec4 matAmbient;
	vec4 matEmissive;
	vec4 sceneAmbient;
	uvec4 lightFlags;
	uvec4 lightInfo;
	vec4 lightDiffuse[4];
	vec4 lightAmbient[4];
	vec4 lightPosType[4];
	vec4 lightDirRange[4];
	vec4 lightAtten[4];
	mat4 worldView;
	mat4 texMatrix[8];
	uvec4 texGen[8];
	vec4 pointParams;
	vec4 pointScale;
} draw;

layout(std140, set = 0, binding = 9) uniform PsConst { vec4 c[32]; } ps;

layout(set = 0, binding = 1) uniform sampler2D waterMap;
layout(set = 0, binding = 2) uniform sampler2D sparkleMap;
layout(set = 0, binding = 3) uniform sampler2D noiseMap;
layout(set = 0, binding = 4) uniform sampler2D maskMap;
layout(set = 0, binding = 5) uniform sampler2D sceneMap;
layout(set = 0, binding = 6) uniform sampler2D depthMap;
layout(set = 0, binding = 7) uniform sampler2D reflMap;

layout(location = 0) in vec4 vDiffuse;
layout(location = 1) in vec4 vUv[8];
layout(location = 0) out vec4 outColor;

#define g_wave   ps.c[1]
#define g_misc   ps.c[2]
#define g_world  ps.c[3]
#define g_height ps.c[4]
#define g_screen ps.c[5]
#define g_refl   ps.c[6]
#define g_axisX  ps.c[8].xyz
#define g_axisY  ps.c[9].xyz
#define g_axisZ  ps.c[10].xyz
#define g_sun    ps.c[11].xyz

float sat(float x) { return clamp(x, 0.0, 1.0); }
vec3 sat3(vec3 x) { return clamp(x, vec3(0.0), vec3(1.0)); }

void main()
{
	vec2 uvWater = vUv[0].xy, uvSparkle = vUv[1].xy, uvNoise = vUv[2].xy, uvMask = vUv[3].xy;
	vec4 projPos = vUv[4];
	vec2 uvDepth = vUv[5].xy;
	vec3 camPos = vUv[6].xyz;
	vec4 vertexColor = vDiffuse;

	float t = g_world.y;
	vec2 world = uvDepth * g_world.zw - g_height.zw;

	// ---- depth below the water surface, in world units
	float terrain = texture(depthMap, uvDepth).r * g_height.y + g_height.x;
	float depth = g_world.x - terrain;

	// ---- waves: a sum of five directional waves with a noise warped phase; slope of each wave is analytic
	vec4 nA = texture(noiseMap, world * 0.0110 + vec2(t * 0.017, t * 0.011));
	vec4 nB = texture(noiseMap, world * 0.0270 + vec2(-t * 0.023, t * 0.019));
	vec4 nC = texture(noiseMap, world * 0.0710 + vec2(t * 0.041, -t * 0.033));
	vec2 warped = world + (nA.rg - 0.5) * 14.0 + (nB.gb - 0.5) * 5.0;
	vec2 slope;
	float crestSum;
	{
		const vec2 d0 = vec2(0.86, 0.51);   const float k0 = 0.105; const float a0 = 0.095; const float w0 = 0.70;
		const vec2 d1 = vec2(0.31, 0.95);   const float k1 = 0.185; const float a1 = 0.080; const float w1 = 0.95;
		const vec2 d2 = vec2(-0.55, 0.84);  const float k2 = 0.300; const float a2 = 0.065; const float w2 = 1.25;
		const vec2 d3 = vec2(0.97, -0.24);  const float k3 = 0.480; const float a3 = 0.050; const float w3 = 1.60;
		const vec2 d4 = vec2(-0.80, -0.60); const float k4 = 0.800; const float a4 = 0.030; const float w4 = 2.10;
		float c0 = cos(k0 * dot(d0, warped) - w0 * t);
		float c1 = cos(k1 * dot(d1, warped) - w1 * t + 1.3);
		float c2 = cos(k2 * dot(d2, warped) - w2 * t + 2.1);
		float c3 = cos(k3 * dot(d3, warped) - w3 * t + 0.4);
		float c4 = cos(k4 * dot(d4, warped) - w4 * t + 4.2);
		slope = d0 * (a0 * c0) + d1 * (a1 * c1) + d2 * (a2 * c2) + d3 * (a3 * c3) + d4 * (a4 * c4);
		crestSum = c0 * 0.40 + c1 * 0.32 + c2 * 0.28;
	}
	slope += (nA.rg - 0.5) * 0.06 + (nB.rg - 0.5) * 0.035;
	slope *= g_wave.w;

	// ---- units on the water: rings spreading from the hull and a V shaped wake with foam behind moving ones
	float wakeFoam = 0.0;
	for (int i = 0; i < 6; i++)
	{
		vec4 ob = ps.c[12 + i];
		vec3 od = ps.c[18 + i].xyz;
		vec2 dv = world - ob.xy;
		float dist = length(dv);
		float radius = ob.z + 1.0;
		float spd = sat(ob.w * 0.045);
		float ringFade = sat(1.0 - dist / (radius * 3.5 + 6.0)) * sat(dist / (radius * 0.5));
		float ring = sin(dist * 1.6 - t * 4.0) * ringFade * (1.0 - spd) * 0.6 * od.z;
		slope += (dv / max(dist, 0.001)) * ring * 0.45;
		float behind = -dot(dv, od.xy);
		float across = dot(dv, vec2(-od.y, od.x));
		float behindMask = sat(behind / (radius * 0.6)) * sat(1.0 - behind / (radius * 7.0 + 40.0));
		float armOffset = (abs(across) - (radius * 0.5 + behind * 0.32)) / (radius * 0.22 + 0.7 + behind * 0.04);
		float coreOffset = across / (radius * 0.55 + 0.6 + behind * 0.10);
		wakeFoam += (exp(-armOffset * armOffset) * 0.9 + exp(-coreOffset * coreOffset) * 0.6) * behindMask * spd * od.z;
	}

	// normal and view vector in camera space
	vec3 normal = normalize(slope.x * g_axisX + slope.y * g_axisY + g_axisZ);
	vec3 incident = normalize(camPos);
	float cosView = sat(dot(normal, -incident));

	// ---- refraction
	vec2 screenUV = (projPos.xy / projPos.w) * g_screen.xy + g_screen.zw;
	vec2 refractUV = screenUV + slope * g_wave.x * sat(depth * 0.6);
	vec3 scene = texture(sceneMap, refractUV).rgb;

	// ---- absorption
	vec3 absorb = vec3(0.34, 0.095, 0.060);
	float optical = max(depth, 0.0) * g_misc.w;
	vec3 transmit = exp(-absorb * optical);
	float depthMix = sat(optical * (1.0 / 9.0));
	vec3 shallowCol = vec3(0.040, 0.420, 0.470);
	vec3 deepCol = vec3(0.010, 0.060, 0.230);
	vec3 waterTint = texture(waterMap, uvWater + slope * 0.02).rgb;
	vec3 inscatter = mix(shallowCol, deepCol, depthMix) * mix(vec3(1.0), waterTint * 1.7, 0.22) * (0.55 + 0.45 * sat(g_sun.z));

	vec3 lightTint = sat3(vertexColor.rgb * 1.9);
#ifdef RIVER
	float shroud = sat(vertexColor.a / max(g_misc.x, 0.001));
	vec4 edge = texture(maskMap, uvMask);
#else
	float shroud = 1.0;
#endif

	vec3 sunCam0 = g_sun.x * g_axisX + g_sun.y * g_axisY + g_sun.z * g_axisZ;
	float waveShade = 0.72 + 0.55 * sat(dot(normal, sunCam0));
	vec3 color = scene * transmit + inscatter * lightTint * waveShade * (1.0 - transmit);

	// ---- fresnel sky reflection
	float fresnel = 0.16 + 0.84 * pow(1.0 - cosView, 3.0);
	vec3 reflected = reflect(incident, normal);
	float skyUp = sat(dot(reflected, g_axisZ));
	vec3 skyColor = mix(vec3(0.62, 0.74, 0.86), vec3(0.20, 0.42, 0.80), pow(skyUp, 0.6));
	vec2 reflUV = projPos.xy / projPos.w + slope * 0.030;
	vec3 mirror = texture(reflMap, reflUV).rgb;
	vec3 envColor = mix(skyColor * lightTint, mirror, g_refl.x);
	color = mix(color, envColor, sat(fresnel * g_wave.z * sat(depth * 2.0)));

	// ---- sun glints
	vec3 sunCam = sunCam0;
	vec3 halfVec = normalize(sunCam - incident);
	float spec = pow(sat(dot(normal, halfVec)), g_misc.z) * g_misc.y;
	vec2 sparkleUV = uvSparkle * 2.7 + slope * 0.05;
	float sparkle = texture(sparkleMap, sparkleUV).r * texture(sparkleMap, sparkleUV * 2.31 + 0.47).r;
	float sunFacing = sat(dot(normal, sunCam));
	color += (spec + sparkle * 2.2 * pow(sunFacing, 14.0)) * vec3(1.0, 0.96, 0.88) * sat(depth * 0.8);

	// ---- foam
	float foamPattern = smoothstep(0.30, 0.78, nA.b * 0.55 + nB.g * 0.55 + nC.r * 0.30);
	float shoreWidth = 0.55 + 0.28 * sin(t * 0.85 + nA.r * 6.28);
	float shoreFoam = sat(1.0 - depth / shoreWidth) * (0.55 + 0.45 * foamPattern);
	float bandPhase = depth * 3.0 - t * 0.85 + nB.r * 2.0;
	float bands = pow(sat(sin(bandPhase)), 5.0) * sat(1.0 - depth * (1.0 / 1.8)) * foamPattern;
	float crest = sat((crestSum - 0.72) * 4.0) * foamPattern * sat(depth * 0.3);
	float foam = sat((shoreFoam + bands * 0.8 + crest * 0.6 + wakeFoam * foamPattern) * g_wave.y);
	color = mix(color, vec3(0.93, 0.97, 1.0) * lightTint, foam);

	// ---- opacity
	float alpha = sat(depth * 4.0 + 0.05);
	alpha = max(alpha, foam * sat(depth * 10.0 + 0.3));
#ifdef RIVER
	alpha *= edge.a;
	color *= shroud;
#else
	color *= texture(maskMap, uvMask).rgb;
#endif
	outColor = vec4(color, alpha);
}
