#version 450
// Native Vulkan backend: the updated water surface. Port of Water/Shaders/WaterModern.hlsl (the Direct3D shader of the DXVK path),
// built twice: -DRIVER for river polygons, -DTRAPEZOID for area water (the sea).
// The engine feeds it exactly like the Direct3D shader: stage textures 0..6, pixel shader constants c1..c23, and texture coordinate
// sets generated by stage transforms (4 = projected position, 5 = height map uv, 6 = camera space position).

layout(std140, set = 0, binding = 0) uniform Draw
{
	mat4 wvp;
	vec4 viewport;
	vec4 textureFactor;
	uvec4 flags;
	vec4 alphaRef;
	uvec4 stage[8];
	mat4 world;
	vec4 matDiffuse;
	vec4 matAmbient;
	vec4 matEmissive;
	vec4 sceneAmbient;
	uvec4 lightFlags;
	uvec4 lightInfo;
	vec4 lightDiffuse[4];
	vec4 lightAmbient[4];
	vec4 lightPosType[4];
	vec4 lightDirRange[4];
	vec4 lightAtten[4];
	mat4 worldView;
	mat4 texMatrix[8];
	uvec4 texGen[8];
	vec4 pointParams;
	vec4 pointScale;
} draw;

layout(std140, set = 0, binding = 9) uniform PsConst { vec4 c[32]; } ps;

layout(set = 0, binding = 1) uniform sampler2D waterMap;
layout(set = 0, binding = 2) uniform sampler2D sparkleMap;
layout(set = 0, binding = 3) uniform sampler2D noiseMap;
layout(set = 0, binding = 4) uniform sampler2D maskMap;
layout(set = 0, binding = 5) uniform sampler2D sceneMap;
layout(set = 0, binding = 6) uniform sampler2D depthMap;
layout(set = 0, binding = 7) uniform sampler2D reflMap;

layout(location = 0) in vec4 vDiffuse;
layout(location = 1) in vec4 vUv[8];
layout(location = 0) out vec4 outColor;

#define g_wave   ps.c[1]
#define g_misc   ps.c[2]
#define g_world  ps.c[3]
#define g_height ps.c[4]
#define g_screen ps.c[5]
#define g_refl   ps.c[6]
#define g_axisX  ps.c[8].xyz
#define g_axisY  ps.c[9].xyz
#define g_axisZ  ps.c[10].xyz
#define g_sun    ps.c[11].xyz

float sat(float x) { return clamp(x, 0.0, 1.0); }
vec3 sat3(vec3 x) { return clamp(x, vec3(0.0), vec3(1.0)); }

// Tileable caustic pattern: bright, thin, moving network of light lines
float caustic(vec2 p, float t)
{
	const float TAU = 6.28318530718;
	vec2 q = mod(p * TAU, TAU) - 250.0;
	vec2 i = q;
	float c = 1.0;
	const float inten = 0.005;
	for (int n = 0; n < 4; n++)
	{
		float tt = t * (1.0 - 3.5 / float(n + 1));
		i = q + vec2(cos(tt - i.x) + sin(tt + i.y), sin(tt - i.y) + cos(tt + i.x));
		c += 1.0 / length(vec2(q.x / (sin(i.x + tt) / inten), q.y / (cos(i.y + tt) / inten)));
	}
	c /= 4.0;
	c = 1.17 - pow(c, 1.4);
	return pow(abs(c), 8.0);
}

// One wave of a sum: height-like value in .x, slope in .yz. Peaked crests (Gerstner-like) through a sharpened sine.
vec3 wave(vec2 p, vec2 dir, float k, float speed, float phase, float t, float sharp)
{
	float a = k * dot(dir, p) - speed * t + phase;
	float s = sin(a);
	float c = cos(a);
	float e = exp(sharp * (s - 1.0));                  // narrow crests, wide troughs
	float dh = sharp * c * e * k;                      // derivative along dir
	return vec3(e, dir * dh);
}

void main()
{
	vec2 uvWater = vUv[0].xy, uvSparkle = vUv[1].xy, uvMask = vUv[3].xy;
	vec4 projPos = vUv[4];
	vec2 uvDepth = vUv[5].xy;
	vec3 camPos = vUv[6].xyz;
	vec4 vertexColor = vDiffuse;

	float t = g_world.y;
	vec2 world = uvDepth * g_world.zw - g_height.zw;

	float terrain = texture(depthMap, uvDepth).r * g_height.y + g_height.x;
	float depth = g_world.x - terrain;

	// ---- waves: swell plus chop, noise-warped so the pattern never reads as a lattice
	vec4 nA = texture(noiseMap, world * 0.0090 + vec2(t * 0.013, t * 0.009));
	vec4 nB = texture(noiseMap, world * 0.0260 + vec2(-t * 0.021, t * 0.017));
	vec4 nC = texture(noiseMap, world * 0.0750 + vec2(t * 0.037, -t * 0.029));
	vec2 warped = world + (nA.rg - 0.5) * 22.0 + (nB.gb - 0.5) * 7.0;

	vec3 w0 = wave(warped, vec2(0.86, 0.51), 0.085, 0.60, 0.0, t, 2.2);
	vec3 w1 = wave(warped, vec2(0.40, 0.92), 0.150, 0.85, 1.3, t, 2.6);
	vec3 w2 = wave(warped, vec2(-0.60, 0.80), 0.260, 1.15, 2.1, t, 2.8);
	vec3 w3 = wave(warped, vec2(0.95, -0.30), 0.430, 1.50, 0.4, t, 3.0);
	vec3 w4 = wave(warped, vec2(-0.82, -0.57), 0.700, 1.95, 4.2, t, 3.0);
	vec3 w5 = wave(warped, vec2(0.15, -0.99), 1.150, 2.60, 5.1, t, 3.0);
	float heightSum = w0.x * 1.00 + w1.x * 0.80 + w2.x * 0.55 + w3.x * 0.35 + w4.x * 0.20 + w5.x * 0.10;
	vec2 slope = w0.yz * 0.45 + w1.yz * 0.34 + w2.yz * 0.22 + w3.yz * 0.13 + w4.yz * 0.07 + w5.yz * 0.035;
	slope += (nA.rg - 0.5) * 0.05 + (nB.rg - 0.5) * 0.03 + (nC.rg - 0.5) * 0.02;
	slope *= g_wave.w * 2.4;
	float crest = sat((heightSum - 1.15) * 1.1);       // how high on a wave crest this pixel sits

	// ---- units on the water: rings from the hull and a V shaped wake with foam behind moving ones
	float wakeFoam = 0.0;
	for (int i = 0; i < 6; i++)
	{
		vec4 ob = ps.c[12 + i];
		vec3 od = ps.c[18 + i].xyz;
		vec2 dv = world - ob.xy;
		float dist = length(dv);
		float radius = ob.z + 1.0;
		float spd = sat(ob.w * 0.045);
		float ringFade = sat(1.0 - dist / (radius * 3.5 + 6.0)) * sat(dist / (radius * 0.5));
		float ring = sin(dist * 0.55 - t * 2.2) * ringFade * (1.0 - spd) * 0.6 * od.z;
		slope += (dv / max(dist, 0.001)) * ring * 0.45;
		float behind = -dot(dv, od.xy);
		float across = dot(dv, vec2(-od.y, od.x));
		float behindMask = sat(behind / (radius * 0.6)) * sat(1.0 - behind / (radius * 7.0 + 40.0));
		float armOffset = (abs(across) - (radius * 0.5 + behind * 0.32)) / (radius * 0.22 + 0.7 + behind * 0.04);
		float coreOffset = across / (radius * 0.55 + 0.6 + behind * 0.10);
		wakeFoam += (exp(-armOffset * armOffset) * 0.9 + exp(-coreOffset * coreOffset) * 0.6) * behindMask * spd * od.z;
	}

	vec3 normal = normalize(slope.x * g_axisX + slope.y * g_axisY + g_axisZ);
	vec3 incident = normalize(camPos);
	float cosView = sat(dot(normal, -incident));
	vec3 sunCam = g_sun.x * g_axisX + g_sun.y * g_axisY + g_sun.z * g_axisZ;
	float sunUp = sat(g_sun.z);

	// light of the day from the vertex colour (the sea mesh is shaded); kept partly so night and dusk still read, but never muddy
	vec3 dayLight = sat3(vertexColor.rgb * 1.9);
	vec3 lightTint = mix(vec3(1.0), dayLight, 0.35) * (0.80 + 0.30 * sunUp);

	// ---- refraction: the scene seen through the wavy surface, calmer right at the shore
	vec2 screenUV = (projPos.xy / projPos.w) * g_screen.xy + g_screen.zw;
	vec2 refractUV = screenUV + slope * g_wave.x * sat(depth * 0.5) * 1.6;
	vec3 scene = texture(sceneMap, refractUV).rgb;

	// ---- caustics on the seabed: bright light lines in the shallows
	float causticMask = sat(1.0 - depth / 5.5) * sat(depth * 3.0);
	vec2 cw = world + (nA.rg - 0.5) * 55.0 + (nB.gb - 0.5) * 16.0;               // warped so the cell pattern never tiles visibly
	vec2 cr = vec2(cw.x * 0.80 - cw.y * 0.60, cw.x * 0.60 + cw.y * 0.80);
	float cau = caustic(cw * 0.034 + slope * 0.5, t * 0.50) * 0.65 + caustic(cr * 0.058 + 7.3, t * 0.75) * 0.45;
	cau *= 0.35 + 1.1 * smoothstep(0.25, 0.75, nA.b * 0.6 + nB.r * 0.5);          // patches of strong and weak light
	scene += cau * causticMask * vec3(0.50, 0.80, 0.76) * (0.5 + 0.5 * sunUp) * 1.1;

	// ---- absorption: red is gone within a few units, blue survives; colours are deliberately saturated
	vec3 absorb = vec3(0.95, 0.24, 0.095);
	float d = max(depth, 0.0);
	vec3 transmit = exp(-absorb * d * 0.60) * 0.78;   // never fully see-through: the sea has body
	float depthMix = 1.0 - exp(-d * 0.30);            // shallow turquoise to deep ocean blue over ~12 units
	vec3 shallowCol = vec3(0.050, 0.700, 0.640);
	vec3 midCol     = vec3(0.012, 0.330, 0.620);
	vec3 deepCol    = vec3(0.004, 0.090, 0.340);
	vec3 bodyCol = mix(mix(shallowCol, midCol, sat(depthMix * 2.0)), deepCol, sat(depthMix * 2.0 - 1.0));
	vec3 waterTint = texture(waterMap, uvWater + slope * 0.02).rgb;
	bodyCol *= mix(vec3(1.0), waterTint * 1.6, 0.12);
	float waveShade = (0.50 + 1.05 * sat(dot(normal, sunCam))) * (0.80 + 0.35 * heightSum);
	vec3 color = scene * transmit + bodyCol * lightTint * waveShade * (1.0 - transmit);

	// ---- subsurface scattering: sun shining through thin wave crests glows turquoise
	float sss = pow(sat(dot(-incident, normalize(sunCam + normal * 0.45))), 3.0) * crest;
	color += vec3(0.05, 0.62, 0.50) * sss * 1.5 * sunUp * lightTint;

	// ---- fresnel sky reflection with a horizon haze
	float fresnel = 0.04 + 0.96 * pow(1.0 - cosView, 3.6);
	vec3 reflected = reflect(incident, normal);
	float skyUp = sat(dot(reflected, g_axisZ));
	vec3 skyColor = mix(vec3(0.70, 0.82, 0.92), vec3(0.16, 0.38, 0.82), pow(skyUp, 0.55));
	vec2 reflUV = projPos.xy / projPos.w + slope * 0.035;
	vec3 mirror = texture(reflMap, reflUV).rgb;
	vec3 envColor = mix(skyColor * lightTint, mirror, g_refl.x);
	color = mix(color, envColor, sat(fresnel * g_wave.z * 1.1 * sat(depth * 2.5)));

	// ---- sun glints: tight highlight plus sparkle
	vec3 halfVec = normalize(sunCam - incident);
	float spec = pow(sat(dot(normal, halfVec)), g_misc.z * 1.5) * g_misc.y * 1.4;
	vec2 sparkleUV = uvSparkle * 2.7 + slope * 0.05;
	float sparkle = texture(sparkleMap, sparkleUV).r * texture(sparkleMap, sparkleUV * 2.31 + 0.47).r;
	float sunFacing = sat(dot(normal, sunCam));
	color += (spec + sparkle * 2.4 * pow(sunFacing, 12.0)) * vec3(1.0, 0.96, 0.88) * sat(depth * 0.8);

	// ---- foam: shore swash lines that run up the beach and fade, foam clouds on the wave crests, wakes
	float foamPattern = smoothstep(0.28, 0.80, nA.b * 0.50 + nB.g * 0.55 + nC.r * 0.40);
	float foamFine = smoothstep(0.35, 0.75, nC.g * 0.6 + nB.r * 0.5);
	float swash = 0.65 + 0.35 * sin(t * 0.9 + nA.r * 6.28);
	float shoreFoam = sat(1.0 - depth / (0.65 * swash + 0.15)) * (0.60 + 0.40 * foamPattern);
	float phase = depth * 2.6 - t * 0.95 + nB.r * 2.4;
	float lines = pow(sat(sin(phase)), 4.0) * sat(1.0 - depth * 0.45) * (0.45 + 0.55 * foamPattern);
	float crestFoam = sat((crest - 0.35) * 2.2) * foamPattern * foamFine * sat(depth * 0.35);
	float foam = sat((shoreFoam + lines * 0.85 + crestFoam * 0.9 + wakeFoam * (0.5 + 0.5 * foamPattern)) * g_wave.y);
	vec3 foamCol = vec3(0.96, 0.99, 1.0) * mix(vec3(0.82), dayLight, 0.45);
	color = mix(color, foamCol, foam);

	// ---- opacity: shore blends into the dry land, foam stays solid just off the beach
	float alpha = sat(depth * 3.5 + 0.04);
	alpha = max(alpha, foam * sat(depth * 10.0 + 0.3));
#ifdef RIVER
	float shroud = sat(vertexColor.a / max(g_misc.x, 0.001));
	vec4 edge = texture(maskMap, uvMask);
	alpha *= edge.a;
	color *= shroud;
#else
	color *= texture(maskMap, uvMask).rgb;
#endif
	outColor = vec4(color, alpha);
}
