# Compiles the GLSL shaders of the native Vulkan backend to SPIR-V and writes them as a C header next to the sources.
# Needs glslang.exe: run tools\dxvk\build-dxvk.ps1 once (it downloads glslang into tools\dxvk\work\tools\glslang) or pass -Glslang.
# The generated header is committed, so a normal build does not need glslang.
param([string]$Glslang = "")
$root = Split-Path $PSScriptRoot -Parent
if (-not $Glslang) { $Glslang = Join-Path $root "tools\dxvk\work\tools\glslang\bin\glslang.exe" }
if (-not (Test-Path $Glslang)) { throw "glslang.exe not found at $Glslang" }

$dir = Join-Path $root "Core\Libraries\Source\WWVegas\WW3D2"
$shaders = @(
    @{ Source = "Shaders\gfx_fixed.vert"; Name = "g_gfxFixedVert" },
    @{ Source = "Shaders\gfx_fixed.frag"; Name = "g_gfxFixedFrag" },
    @{ Source = "Shaders\gfx_post.vert"; Name = "g_gfxPostVert" },
    @{ Source = "Shaders\gfx_post.frag"; Name = "g_gfxPostBloomDown0Frag"; Define = "PASS_BLOOM_DOWN0" },
    @{ Source = "Shaders\gfx_post.frag"; Name = "g_gfxPostBloomDownFrag"; Define = "PASS_BLOOM_DOWN" },
    @{ Source = "Shaders\gfx_post.frag"; Name = "g_gfxPostBloomUpFrag"; Define = "PASS_BLOOM_UP" },
    @{ Source = "Shaders\gfx_post.frag"; Name = "g_gfxPostCompositeFrag"; Define = "PASS_COMPOSITE" },
    @{ Source = "Shaders\gfx_post.frag"; Name = "g_gfxPostFxaaFrag"; Define = "PASS_FXAA" },
    @{ Source = "Shaders\gfx_post.frag"; Name = "g_gfxPostShadowFrag"; Define = "PASS_SHADOW" },
    @{ Source = "Shaders\gfx_post.frag"; Name = "g_gfxPostAoFrag"; Define = "PASS_AO" },
    @{ Source = "Shaders\gfx_post.frag"; Name = "g_gfxPostAoBlurFrag"; Define = "PASS_AOBLUR" },
    @{ Source = "Shaders\gfx_water.frag"; Name = "g_gfxWaterRiverFrag"; Define = "RIVER" },
    @{ Source = "Shaders\gfx_water.frag"; Name = "g_gfxWaterTrapezoidFrag"; Define = "TRAPEZOID" }
)
$text = "// Generated by scripts/compile-vk-shaders.ps1 from the files in Shaders/. Do not edit.`r`n#pragma once`r`n`r`n"
foreach ($s in $shaders) {
    $src = Join-Path $dir $s.Source
    $tmp = [IO.Path]::GetTempFileName()
    $defs = @()
    if ($s.Define) { $defs = @("-D$($s.Define)") }
    & $Glslang -V --target-env vulkan1.3 @defs -o $tmp $src
    if ($LASTEXITCODE -ne 0) { throw "glslang failed for $src" }
    $bytes = [IO.File]::ReadAllBytes($tmp)
    Remove-Item $tmp -Force
    $words = for ($i = 0; $i -lt $bytes.Length; $i += 4) { "0x{0:X8}" -f [BitConverter]::ToUInt32($bytes, $i) }
    $lines = for ($i = 0; $i -lt $words.Count; $i += 8) { "`t" + (($words[$i..([Math]::Min($i + 7, $words.Count - 1))]) -join ", ") + "," }
    $text += "static const unsigned int $($s.Name)[] =`r`n{`r`n" + ($lines -join "`r`n") + "`r`n};`r`n`r`n"
    "$($s.Name): $($bytes.Length) bytes"
}
[IO.File]::WriteAllText((Join-Path $dir "gfx_vk_shaders.h"), $text)
