# Compiles the HLSL shaders of the renderer to Direct3D 9 shader bytecode and writes C headers next to the sources.
# Needs fxc.exe from the Windows SDK. The generated headers are committed so a normal build does not need fxc.
$root = Split-Path $PSScriptRoot -Parent
$fxc = Get-ChildItem "${env:ProgramFiles(x86)}\Windows Kits\10\bin" -Recurse -Filter fxc.exe -ErrorAction SilentlyContinue |
    Where-Object { $_.FullName -match '\\x64\\' } | Sort-Object FullName -Descending | Select-Object -First 1
if (-not $fxc) { throw "fxc.exe (Windows SDK) not found" }

$dir = "Core\GameEngineDevice\Source\W3DDevice\GameClient\Water\Shaders"
$shaders = @(
    @{ Source = "$dir\WaterModern.hlsl"; Profile = "ps_3_0"; Name = "g_waterModernRiverPS";     Header = "WaterModernRiverPS.h";      Defines = @("/D", "RIVER") },
    @{ Source = "$dir\WaterModern.hlsl"; Profile = "ps_3_0"; Name = "g_waterModernTrapezoidPS"; Header = "WaterModernTrapezoidPS.h"; Defines = @("/D", "TRAPEZOID") }
)

foreach ($s in $shaders) {
    $src = Join-Path $root $s.Source
    $tmp = [IO.Path]::GetTempFileName()
    & $fxc.FullName /nologo /T $s.Profile /E main /O3 @($s.Defines) /Fo $tmp $src
    if ($LASTEXITCODE -ne 0) { throw "fxc failed for $src" }
    $bytes = [IO.File]::ReadAllBytes($tmp)
    Remove-Item $tmp -Force
    $words = for ($i = 0; $i -lt $bytes.Length; $i += 4) { "0x{0:X8}" -f [BitConverter]::ToUInt32($bytes, $i) }
    $lines = for ($i = 0; $i -lt $words.Count; $i += 6) { "`t" + (($words[$i..([Math]::Min($i + 5, $words.Count - 1))]) -join ", ") + "," }
    $header = Join-Path (Split-Path $src -Parent) $s.Header
    $text = "// Generated by scripts/compile-shaders.ps1 from $([IO.Path]::GetFileName($src)) ($($s.Profile) $($s.Defines -join ' ')). Do not edit.`r`n#pragma once`r`n`r`nstatic const unsigned long $($s.Name)[] =`r`n{`r`n" + ($lines -join "`r`n") + "`r`n};`r`n"
    [IO.File]::WriteAllText($header, $text)
    "$($s.Name): $($bytes.Length) bytes -> $header"
}
