import re, sys, os

import sys
REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
HDR = sys.argv[1] if len(sys.argv) > 1 else os.path.join(REPO, 'build', 'win64-vcpkg', '_deps', 'dx8-src', 'd3d8.h')
OUT = os.path.join(REPO, 'Core', 'Libraries', 'Source', 'WWVegas', 'WW3D2', 'gfx_null_stubs.inl')
text = open(HDR, encoding='latin-1').read().replace('\r\n', '\n')

# collect interfaces: name -> (parent, [method lines])
iface = {}
for m in re.finditer(r'DECLARE_INTERFACE_\((\w+),\s*(\w+)\)\s*\{(.*?)\n\};', text, re.S):
    name, parent, body = m.group(1), m.group(2), m.group(3)
    methods = []
    for line in body.split('\n'):
        line = line.strip()
        mm = re.match(r'STDMETHOD(_\(([^,]+),\s*(\w+)\)|\((\w+)\))\((THIS_?)(.*?)\)\s*PURE;', line)
        if not mm:
            continue
        ret = mm.group(2).strip() if mm.group(2) else 'HRESULT'
        mname = mm.group(3) or mm.group(4)
        params = mm.group(6).strip()
        methods.append((ret, mname, params, mm.group(5)))
    iface[name] = (parent, methods)

def all_methods(name):
    if name not in iface:
        return []
    parent, methods = iface[name]
    return all_methods(parent) + methods

def default_body(ret, name):
    r = ret.replace(' ', '')
    if r == 'HRESULT':
        return 'return D3D_OK;'
    if r == 'void':
        return ''
    if r in ('ULONG', 'UINT', 'DWORD', 'int', 'BOOL'):
        return 'return 0;'
    if r == 'HMONITOR':
        return 'return nullptr;'
    if r == 'D3DRESOURCETYPE':
        return 'return D3DRTYPE_SURFACE;'
    if r == 'D3DFORMAT':
        return 'return D3DFMT_UNKNOWN;'
    if r.endswith('*'):
        return 'return nullptr;'
    return 'return (%s)0;' % ret

TARGETS = ['IDirect3D8', 'IDirect3DDevice8', 'IDirect3DSurface8', 'IDirect3DTexture8', 'IDirect3DVolumeTexture8',
           'IDirect3DCubeTexture8', 'IDirect3DVertexBuffer8', 'IDirect3DIndexBuffer8', 'IDirect3DSwapChain8']
out = ['// Generated by scripts/gen_null_stubs.py from d3d8.h. Do not edit.',
       '// Base classes that implement every method of a Direct3D 8 interface with a harmless default (success / 0 / nothing).',
       '// gfx_null.cpp derives from these and overrides what the null graphics backend really has to do.', '']
for t in TARGETS:
    ms = all_methods(t)
    seen = set()
    out.append('class %sNullBase : public %s' % (t, t))
    out.append('{')
    out.append('public:')
    for ret, name, params, this in ms:
        if name in ('QueryInterface', 'AddRef', 'Release'):
            continue      # reference counting is written by hand
        if name in seen:
            continue
        seen.add(name)
        p = ('THIS_ ' + params) if params else 'THIS'
        if ret == 'HRESULT':
            sig = 'STDMETHOD(%s)(%s)' % (name, p)
        else:
            sig = 'STDMETHOD_(%s, %s)(%s)' % (ret, name, p)
        # unused parameter warnings are errors in this project: mark them by omitting names is not possible, so use the macro
        body = default_body(ret, name)
        out.append('	%s override { NULLGFX_UNUSED_PARAMS; %s }' % (sig, body))
    out.append('};')
    out.append('')
open(OUT, 'w', encoding='latin-1', newline='').write('\r\n'.join(out))
print('generated', len(TARGETS), 'classes,', sum(len(all_methods(t)) for t in TARGETS), 'methods ->', OUT)
