// Generated by scripts/gen_null_stubs.py from d3d8.h. Do not edit.
// Base classes that implement every method of a Direct3D 8 interface with a harmless default (success / 0 / nothing).
// gfx_null.cpp derives from these and overrides what the null graphics backend really has to do.

class IDirect3D8NullBase : public IDirect3D8
{
public:
	STDMETHOD(RegisterSoftwareDevice)(THIS_ void* pInitializeFunction) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD_(UINT, GetAdapterCount)(THIS) override { NULLGFX_UNUSED_PARAMS; return 0; }
	STDMETHOD(GetAdapterIdentifier)(THIS_ UINT Adapter,DWORD Flags,D3DADAPTER_IDENTIFIER8* pIdentifier) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD_(UINT, GetAdapterModeCount)(THIS_ UINT Adapter) override { NULLGFX_UNUSED_PARAMS; return 0; }
	STDMETHOD(EnumAdapterModes)(THIS_ UINT Adapter,UINT Mode,D3DDISPLAYMODE* pMode) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(GetAdapterDisplayMode)(THIS_ UINT Adapter,D3DDISPLAYMODE* pMode) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(CheckDeviceType)(THIS_ UINT Adapter,D3DDEVTYPE CheckType,D3DFORMAT DisplayFormat,D3DFORMAT BackBufferFormat,BOOL Windowed) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(CheckDeviceFormat)(THIS_ UINT Adapter,D3DDEVTYPE DeviceType,D3DFORMAT AdapterFormat,DWORD Usage,D3DRESOURCETYPE RType,D3DFORMAT CheckFormat) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(CheckDeviceMultiSampleType)(THIS_ UINT Adapter,D3DDEVTYPE DeviceType,D3DFORMAT SurfaceFormat,BOOL Windowed,D3DMULTISAMPLE_TYPE MultiSampleType) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(CheckDepthStencilMatch)(THIS_ UINT Adapter,D3DDEVTYPE DeviceType,D3DFORMAT AdapterFormat,D3DFORMAT RenderTargetFormat,D3DFORMAT DepthStencilFormat) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(GetDeviceCaps)(THIS_ UINT Adapter,D3DDEVTYPE DeviceType,D3DCAPS8* pCaps) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD_(HMONITOR, GetAdapterMonitor)(THIS_ UINT Adapter) override { NULLGFX_UNUSED_PARAMS; return nullptr; }
	STDMETHOD(CreateDevice)(THIS_ UINT Adapter,D3DDEVTYPE DeviceType,HWND hFocusWindow,DWORD BehaviorFlags,D3DPRESENT_PARAMETERS* pPresentationParameters,IDirect3DDevice8** ppReturnedDeviceInterface) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
};

class IDirect3DDevice8NullBase : public IDirect3DDevice8
{
public:
	STDMETHOD(TestCooperativeLevel)(THIS) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD_(UINT, GetAvailableTextureMem)(THIS) override { NULLGFX_UNUSED_PARAMS; return 0; }
	STDMETHOD(ResourceManagerDiscardBytes)(THIS_ DWORD Bytes) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(GetDirect3D)(THIS_ IDirect3D8** ppD3D8) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(GetDeviceCaps)(THIS_ D3DCAPS8* pCaps) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(GetDisplayMode)(THIS_ D3DDISPLAYMODE* pMode) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(GetCreationParameters)(THIS_ D3DDEVICE_CREATION_PARAMETERS *pParameters) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(SetCursorProperties)(THIS_ UINT XHotSpot,UINT YHotSpot,IDirect3DSurface8* pCursorBitmap) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD_(void, SetCursorPosition)(THIS_ UINT XScreenSpace,UINT YScreenSpace,DWORD Flags) override { NULLGFX_UNUSED_PARAMS;  }
	STDMETHOD_(BOOL, ShowCursor)(THIS_ BOOL bShow) override { NULLGFX_UNUSED_PARAMS; return 0; }
	STDMETHOD(CreateAdditionalSwapChain)(THIS_ D3DPRESENT_PARAMETERS* pPresentationParameters,IDirect3DSwapChain8** pSwapChain) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(Reset)(THIS_ D3DPRESENT_PARAMETERS* pPresentationParameters) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(Present)(THIS_ CONST RECT* pSourceRect,CONST RECT* pDestRect,HWND hDestWindowOverride,CONST RGNDATA* pDirtyRegion) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(GetBackBuffer)(THIS_ UINT BackBuffer,D3DBACKBUFFER_TYPE Type,IDirect3DSurface8** ppBackBuffer) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(GetRasterStatus)(THIS_ D3DRASTER_STATUS* pRasterStatus) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD_(void, SetGammaRamp)(THIS_ DWORD Flags,CONST D3DGAMMARAMP* pRamp) override { NULLGFX_UNUSED_PARAMS;  }
	STDMETHOD_(void, GetGammaRamp)(THIS_ D3DGAMMARAMP* pRamp) override { NULLGFX_UNUSED_PARAMS;  }
	STDMETHOD(CreateTexture)(THIS_ UINT Width,UINT Height,UINT Levels,DWORD Usage,D3DFORMAT Format,D3DPOOL Pool,IDirect3DTexture8** ppTexture) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(CreateVolumeTexture)(THIS_ UINT Width,UINT Height,UINT Depth,UINT Levels,DWORD Usage,D3DFORMAT Format,D3DPOOL Pool,IDirect3DVolumeTexture8** ppVolumeTexture) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(CreateCubeTexture)(THIS_ UINT EdgeLength,UINT Levels,DWORD Usage,D3DFORMAT Format,D3DPOOL Pool,IDirect3DCubeTexture8** ppCubeTexture) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(CreateVertexBuffer)(THIS_ UINT Length,DWORD Usage,DWORD FVF,D3DPOOL Pool,IDirect3DVertexBuffer8** ppVertexBuffer) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(CreateIndexBuffer)(THIS_ UINT Length,DWORD Usage,D3DFORMAT Format,D3DPOOL Pool,IDirect3DIndexBuffer8** ppIndexBuffer) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(CreateRenderTarget)(THIS_ UINT Width,UINT Height,D3DFORMAT Format,D3DMULTISAMPLE_TYPE MultiSample,BOOL Lockable,IDirect3DSurface8** ppSurface) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(CreateDepthStencilSurface)(THIS_ UINT Width,UINT Height,D3DFORMAT Format,D3DMULTISAMPLE_TYPE MultiSample,IDirect3DSurface8** ppSurface) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(CreateImageSurface)(THIS_ UINT Width,UINT Height,D3DFORMAT Format,IDirect3DSurface8** ppSurface) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(CopyRects)(THIS_ IDirect3DSurface8* pSourceSurface,CONST RECT* pSourceRectsArray,UINT cRects,IDirect3DSurface8* pDestinationSurface,CONST POINT* pDestPointsArray) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(UpdateTexture)(THIS_ IDirect3DBaseTexture8* pSourceTexture,IDirect3DBaseTexture8* pDestinationTexture) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(GetFrontBuffer)(THIS_ IDirect3DSurface8* pDestSurface) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(SetRenderTarget)(THIS_ IDirect3DSurface8* pRenderTarget,IDirect3DSurface8* pNewZStencil) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(GetRenderTarget)(THIS_ IDirect3DSurface8** ppRenderTarget) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(GetDepthStencilSurface)(THIS_ IDirect3DSurface8** ppZStencilSurface) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(BeginScene)(THIS) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(EndScene)(THIS) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(Clear)(THIS_ DWORD Count,CONST D3DRECT* pRects,DWORD Flags,D3DCOLOR Color,float Z,DWORD Stencil) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(SetTransform)(THIS_ D3DTRANSFORMSTATETYPE State,CONST D3DMATRIX* pMatrix) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(GetTransform)(THIS_ D3DTRANSFORMSTATETYPE State,D3DMATRIX* pMatrix) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(MultiplyTransform)(THIS_ D3DTRANSFORMSTATETYPE,CONST D3DMATRIX*) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(SetViewport)(THIS_ CONST D3DVIEWPORT8* pViewport) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(GetViewport)(THIS_ D3DVIEWPORT8* pViewport) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(SetMaterial)(THIS_ CONST D3DMATERIAL8* pMaterial) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(GetMaterial)(THIS_ D3DMATERIAL8* pMaterial) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(SetLight)(THIS_ DWORD Index,CONST D3DLIGHT8*) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(GetLight)(THIS_ DWORD Index,D3DLIGHT8*) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(LightEnable)(THIS_ DWORD Index,BOOL Enable) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(GetLightEnable)(THIS_ DWORD Index,BOOL* pEnable) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(SetClipPlane)(THIS_ DWORD Index,CONST float* pPlane) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(GetClipPlane)(THIS_ DWORD Index,float* pPlane) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(SetRenderState)(THIS_ D3DRENDERSTATETYPE State,DWORD Value) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(GetRenderState)(THIS_ D3DRENDERSTATETYPE State,DWORD* pValue) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(BeginStateBlock)(THIS) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(EndStateBlock)(THIS_ DWORD* pToken) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(ApplyStateBlock)(THIS_ DWORD Token) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(CaptureStateBlock)(THIS_ DWORD Token) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(DeleteStateBlock)(THIS_ DWORD Token) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(CreateStateBlock)(THIS_ D3DSTATEBLOCKTYPE Type,DWORD* pToken) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(SetClipStatus)(THIS_ CONST D3DCLIPSTATUS8* pClipStatus) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(GetClipStatus)(THIS_ D3DCLIPSTATUS8* pClipStatus) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(GetTexture)(THIS_ DWORD Stage,IDirect3DBaseTexture8** ppTexture) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(SetTexture)(THIS_ DWORD Stage,IDirect3DBaseTexture8* pTexture) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(GetTextureStageState)(THIS_ DWORD Stage,D3DTEXTURESTAGESTATETYPE Type,DWORD* pValue) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(SetTextureStageState)(THIS_ DWORD Stage,D3DTEXTURESTAGESTATETYPE Type,DWORD Value) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(ValidateDevice)(THIS_ DWORD* pNumPasses) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(GetInfo)(THIS_ DWORD DevInfoID,void* pDevInfoStruct,DWORD DevInfoStructSize) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(SetPaletteEntries)(THIS_ UINT PaletteNumber,CONST PALETTEENTRY* pEntries) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(GetPaletteEntries)(THIS_ UINT PaletteNumber,PALETTEENTRY* pEntries) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(SetCurrentTexturePalette)(THIS_ UINT PaletteNumber) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(GetCurrentTexturePalette)(THIS_ UINT *PaletteNumber) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(DrawPrimitive)(THIS_ D3DPRIMITIVETYPE PrimitiveType,UINT StartVertex,UINT PrimitiveCount) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(DrawIndexedPrimitive)(THIS_ D3DPRIMITIVETYPE,UINT minIndex,UINT NumVertices,UINT startIndex,UINT primCount) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(DrawPrimitiveUP)(THIS_ D3DPRIMITIVETYPE PrimitiveType,UINT PrimitiveCount,CONST void* pVertexStreamZeroData,UINT VertexStreamZeroStride) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(DrawIndexedPrimitiveUP)(THIS_ D3DPRIMITIVETYPE PrimitiveType,UINT MinVertexIndex,UINT NumVertexIndices,UINT PrimitiveCount,CONST void* pIndexData,D3DFORMAT IndexDataFormat,CONST void* pVertexStreamZeroData,UINT VertexStreamZeroStride) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(ProcessVertices)(THIS_ UINT SrcStartIndex,UINT DestIndex,UINT VertexCount,IDirect3DVertexBuffer8* pDestBuffer,DWORD Flags) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(CreateVertexShader)(THIS_ CONST DWORD* pDeclaration,CONST DWORD* pFunction,DWORD* pHandle,DWORD Usage) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(SetVertexShader)(THIS_ DWORD Handle) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(GetVertexShader)(THIS_ DWORD* pHandle) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(DeleteVertexShader)(THIS_ DWORD Handle) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(SetVertexShaderConstant)(THIS_ DWORD Register,CONST void* pConstantData,DWORD ConstantCount) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(GetVertexShaderConstant)(THIS_ DWORD Register,void* pConstantData,DWORD ConstantCount) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(GetVertexShaderDeclaration)(THIS_ DWORD Handle,void* pData,DWORD* pSizeOfData) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(GetVertexShaderFunction)(THIS_ DWORD Handle,void* pData,DWORD* pSizeOfData) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(SetStreamSource)(THIS_ UINT StreamNumber,IDirect3DVertexBuffer8* pStreamData,UINT Stride) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(GetStreamSource)(THIS_ UINT StreamNumber,IDirect3DVertexBuffer8** ppStreamData,UINT* pStride) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(SetIndices)(THIS_ IDirect3DIndexBuffer8* pIndexData,UINT BaseVertexIndex) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(GetIndices)(THIS_ IDirect3DIndexBuffer8** ppIndexData,UINT* pBaseVertexIndex) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(CreatePixelShader)(THIS_ CONST DWORD* pFunction,DWORD* pHandle) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(SetPixelShader)(THIS_ DWORD Handle) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(GetPixelShader)(THIS_ DWORD* pHandle) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(DeletePixelShader)(THIS_ DWORD Handle) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(SetPixelShaderConstant)(THIS_ DWORD Register,CONST void* pConstantData,DWORD ConstantCount) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(GetPixelShaderConstant)(THIS_ DWORD Register,void* pConstantData,DWORD ConstantCount) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(GetPixelShaderFunction)(THIS_ DWORD Handle,void* pData,DWORD* pSizeOfData) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(DrawRectPatch)(THIS_ UINT Handle,CONST float* pNumSegs,CONST D3DRECTPATCH_INFO* pRectPatchInfo) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(DrawTriPatch)(THIS_ UINT Handle,CONST float* pNumSegs,CONST D3DTRIPATCH_INFO* pTriPatchInfo) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(DeletePatch)(THIS_ UINT Handle) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
};

class IDirect3DSurface8NullBase : public IDirect3DSurface8
{
public:
	STDMETHOD(GetDevice)(THIS_ IDirect3DDevice8** ppDevice) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(SetPrivateData)(THIS_ REFGUID refguid,CONST void* pData,DWORD SizeOfData,DWORD Flags) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(GetPrivateData)(THIS_ REFGUID refguid,void* pData,DWORD* pSizeOfData) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(FreePrivateData)(THIS_ REFGUID refguid) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(GetContainer)(THIS_ REFIID riid,void** ppContainer) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(GetDesc)(THIS_ D3DSURFACE_DESC *pDesc) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(LockRect)(THIS_ D3DLOCKED_RECT* pLockedRect,CONST RECT* pRect,DWORD Flags) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(UnlockRect)(THIS) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
};

class IDirect3DTexture8NullBase : public IDirect3DTexture8
{
public:
	STDMETHOD(GetDevice)(THIS_ IDirect3DDevice8** ppDevice) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(SetPrivateData)(THIS_ REFGUID refguid,CONST void* pData,DWORD SizeOfData,DWORD Flags) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(GetPrivateData)(THIS_ REFGUID refguid,void* pData,DWORD* pSizeOfData) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(FreePrivateData)(THIS_ REFGUID refguid) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD_(DWORD, SetPriority)(THIS_ DWORD PriorityNew) override { NULLGFX_UNUSED_PARAMS; return 0; }
	STDMETHOD_(DWORD, GetPriority)(THIS) override { NULLGFX_UNUSED_PARAMS; return 0; }
	STDMETHOD_(void, PreLoad)(THIS) override { NULLGFX_UNUSED_PARAMS;  }
	STDMETHOD_(D3DRESOURCETYPE, GetType)(THIS) override { NULLGFX_UNUSED_PARAMS; return D3DRTYPE_SURFACE; }
	STDMETHOD_(DWORD, SetLOD)(THIS_ DWORD LODNew) override { NULLGFX_UNUSED_PARAMS; return 0; }
	STDMETHOD_(DWORD, GetLOD)(THIS) override { NULLGFX_UNUSED_PARAMS; return 0; }
	STDMETHOD_(DWORD, GetLevelCount)(THIS) override { NULLGFX_UNUSED_PARAMS; return 0; }
	STDMETHOD(GetLevelDesc)(THIS_ UINT Level,D3DSURFACE_DESC *pDesc) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(GetSurfaceLevel)(THIS_ UINT Level,IDirect3DSurface8** ppSurfaceLevel) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(LockRect)(THIS_ UINT Level,D3DLOCKED_RECT* pLockedRect,CONST RECT* pRect,DWORD Flags) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(UnlockRect)(THIS_ UINT Level) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(AddDirtyRect)(THIS_ CONST RECT* pDirtyRect) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
};

class IDirect3DVolumeTexture8NullBase : public IDirect3DVolumeTexture8
{
public:
	STDMETHOD(GetDevice)(THIS_ IDirect3DDevice8** ppDevice) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(SetPrivateData)(THIS_ REFGUID refguid,CONST void* pData,DWORD SizeOfData,DWORD Flags) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(GetPrivateData)(THIS_ REFGUID refguid,void* pData,DWORD* pSizeOfData) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(FreePrivateData)(THIS_ REFGUID refguid) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD_(DWORD, SetPriority)(THIS_ DWORD PriorityNew) override { NULLGFX_UNUSED_PARAMS; return 0; }
	STDMETHOD_(DWORD, GetPriority)(THIS) override { NULLGFX_UNUSED_PARAMS; return 0; }
	STDMETHOD_(void, PreLoad)(THIS) override { NULLGFX_UNUSED_PARAMS;  }
	STDMETHOD_(D3DRESOURCETYPE, GetType)(THIS) override { NULLGFX_UNUSED_PARAMS; return D3DRTYPE_SURFACE; }
	STDMETHOD_(DWORD, SetLOD)(THIS_ DWORD LODNew) override { NULLGFX_UNUSED_PARAMS; return 0; }
	STDMETHOD_(DWORD, GetLOD)(THIS) override { NULLGFX_UNUSED_PARAMS; return 0; }
	STDMETHOD_(DWORD, GetLevelCount)(THIS) override { NULLGFX_UNUSED_PARAMS; return 0; }
	STDMETHOD(GetLevelDesc)(THIS_ UINT Level,D3DVOLUME_DESC *pDesc) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(GetVolumeLevel)(THIS_ UINT Level,IDirect3DVolume8** ppVolumeLevel) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(LockBox)(THIS_ UINT Level,D3DLOCKED_BOX* pLockedVolume,CONST D3DBOX* pBox,DWORD Flags) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(UnlockBox)(THIS_ UINT Level) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(AddDirtyBox)(THIS_ CONST D3DBOX* pDirtyBox) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
};

class IDirect3DCubeTexture8NullBase : public IDirect3DCubeTexture8
{
public:
	STDMETHOD(GetDevice)(THIS_ IDirect3DDevice8** ppDevice) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(SetPrivateData)(THIS_ REFGUID refguid,CONST void* pData,DWORD SizeOfData,DWORD Flags) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(GetPrivateData)(THIS_ REFGUID refguid,void* pData,DWORD* pSizeOfData) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(FreePrivateData)(THIS_ REFGUID refguid) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD_(DWORD, SetPriority)(THIS_ DWORD PriorityNew) override { NULLGFX_UNUSED_PARAMS; return 0; }
	STDMETHOD_(DWORD, GetPriority)(THIS) override { NULLGFX_UNUSED_PARAMS; return 0; }
	STDMETHOD_(void, PreLoad)(THIS) override { NULLGFX_UNUSED_PARAMS;  }
	STDMETHOD_(D3DRESOURCETYPE, GetType)(THIS) override { NULLGFX_UNUSED_PARAMS; return D3DRTYPE_SURFACE; }
	STDMETHOD_(DWORD, SetLOD)(THIS_ DWORD LODNew) override { NULLGFX_UNUSED_PARAMS; return 0; }
	STDMETHOD_(DWORD, GetLOD)(THIS) override { NULLGFX_UNUSED_PARAMS; return 0; }
	STDMETHOD_(DWORD, GetLevelCount)(THIS) override { NULLGFX_UNUSED_PARAMS; return 0; }
	STDMETHOD(GetLevelDesc)(THIS_ UINT Level,D3DSURFACE_DESC *pDesc) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(GetCubeMapSurface)(THIS_ D3DCUBEMAP_FACES FaceType,UINT Level,IDirect3DSurface8** ppCubeMapSurface) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(LockRect)(THIS_ D3DCUBEMAP_FACES FaceType,UINT Level,D3DLOCKED_RECT* pLockedRect,CONST RECT* pRect,DWORD Flags) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(UnlockRect)(THIS_ D3DCUBEMAP_FACES FaceType,UINT Level) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(AddDirtyRect)(THIS_ D3DCUBEMAP_FACES FaceType,CONST RECT* pDirtyRect) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
};

class IDirect3DVertexBuffer8NullBase : public IDirect3DVertexBuffer8
{
public:
	STDMETHOD(GetDevice)(THIS_ IDirect3DDevice8** ppDevice) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(SetPrivateData)(THIS_ REFGUID refguid,CONST void* pData,DWORD SizeOfData,DWORD Flags) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(GetPrivateData)(THIS_ REFGUID refguid,void* pData,DWORD* pSizeOfData) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(FreePrivateData)(THIS_ REFGUID refguid) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD_(DWORD, SetPriority)(THIS_ DWORD PriorityNew) override { NULLGFX_UNUSED_PARAMS; return 0; }
	STDMETHOD_(DWORD, GetPriority)(THIS) override { NULLGFX_UNUSED_PARAMS; return 0; }
	STDMETHOD_(void, PreLoad)(THIS) override { NULLGFX_UNUSED_PARAMS;  }
	STDMETHOD_(D3DRESOURCETYPE, GetType)(THIS) override { NULLGFX_UNUSED_PARAMS; return D3DRTYPE_SURFACE; }
	STDMETHOD(Lock)(THIS_ UINT OffsetToLock,UINT SizeToLock,BYTE** ppbData,DWORD Flags) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(Unlock)(THIS) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(GetDesc)(THIS_ D3DVERTEXBUFFER_DESC *pDesc) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
};

class IDirect3DIndexBuffer8NullBase : public IDirect3DIndexBuffer8
{
public:
	STDMETHOD(GetDevice)(THIS_ IDirect3DDevice8** ppDevice) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(SetPrivateData)(THIS_ REFGUID refguid,CONST void* pData,DWORD SizeOfData,DWORD Flags) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(GetPrivateData)(THIS_ REFGUID refguid,void* pData,DWORD* pSizeOfData) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(FreePrivateData)(THIS_ REFGUID refguid) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD_(DWORD, SetPriority)(THIS_ DWORD PriorityNew) override { NULLGFX_UNUSED_PARAMS; return 0; }
	STDMETHOD_(DWORD, GetPriority)(THIS) override { NULLGFX_UNUSED_PARAMS; return 0; }
	STDMETHOD_(void, PreLoad)(THIS) override { NULLGFX_UNUSED_PARAMS;  }
	STDMETHOD_(D3DRESOURCETYPE, GetType)(THIS) override { NULLGFX_UNUSED_PARAMS; return D3DRTYPE_SURFACE; }
	STDMETHOD(Lock)(THIS_ UINT OffsetToLock,UINT SizeToLock,BYTE** ppbData,DWORD Flags) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(Unlock)(THIS) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(GetDesc)(THIS_ D3DINDEXBUFFER_DESC *pDesc) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
};

class IDirect3DSwapChain8NullBase : public IDirect3DSwapChain8
{
public:
	STDMETHOD(Present)(THIS_ CONST RECT* pSourceRect,CONST RECT* pDestRect,HWND hDestWindowOverride,CONST RGNDATA* pDirtyRegion) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
	STDMETHOD(GetBackBuffer)(THIS_ UINT BackBuffer,D3DBACKBUFFER_TYPE Type,IDirect3DSurface8** ppBackBuffer) override { NULLGFX_UNUSED_PARAMS; return D3D_OK; }
};
